all:
	$(MAKE) -C Engine
	$(MAKE) -C Editor

ENGINE_LINUX_RELEASE:
	$(MAKE) -C Engine LINUX_RELEASE
ENGINE_LINUX_DEBUG:
	$(MAKE) -C Engine LINUX_DEBUG
ENGINE_WINDOWS_RELEASE:
	$(MAKE) -C Engine WINDOWS_RELEASE
ENGINE_WINDOWS_DEBUG:
	$(MAKE) -C Engine WINDOWS_DEBUG

EDITOR_LINUX_RELEASE: ENGINE_LINUX_RELEASE
	$(MAKE) -C Editor LINUX_RELEASE
EDITOR_LINUX_DEBUG: ENGINE_LINUX_DEBUG
	$(MAKE) -C Editor LINUX_DEBUG
EDITOR_WINDOWS_RELEASE: ENGINE_WINDOWS_RELEASE
	$(MAKE) -C Editor WINDOWS_RELEASE
EDITOR_WINDOWS_DEBUG: ENGINE_WINDOWS_DEBUG
	$(MAKE) -C Editor WINDOWS_DEBUG

clean:
	$(MAKE) -C Engine clean
	$(MAKE) -C Editor clean