name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install -y g++ build-essential libglfw3-dev libglew-dev libglm-dev mingw-w64

    - name: Build engine
      run: make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Jint-Game-Engine_Linux-x86_64
        path: bin/Linux/x86_64/Release/Jint-Game-Engine_Linux-x86_64
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Jint-Game-Engine_Linux-x86_64_Debug
        path: bin/Linux/x86_64/Debug/Jint-Game-Engine_Linux-x86_64_Debug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Jint-Game-Engine_Windows-x86_64
        path: bin/Windows/x86_64/Release/Jint-Game-Engine_Windows-x86_64.exe
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Jint-Game-Engine_Windows-x86_64_Debug
        path: bin/Windows/x86_64/Debug/Jint-Game-Engine_Windows-x86_64_Debug.exe
