name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install -y g++ build-essential libglfw3-dev libglew-dev libglm-dev

    - name: Build engine
      run: make release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Jint-Game-Engine
        path: bin/Release/Jint-Game-Engine
